#!/usr/bin/env ruby

JEKYLL_HOME="/Users/maryh/Documents/jekyll/coldandheartless"

puts "Did you remember to run jekyll s to regenerate the site?"
puts "rsync of coldandheartless.com running"

output=`time /usr/bin/rsync \
	--rsh=/usr/bin/ssh \
	--archive \
	--compress \
	--delete \
	"#{JEKYLL_HOME}"/_site/* pickabout.com:/var/www/html/coldandheartless`

puts "#{output}"